добавлен сервис статистики
Natal1a-Chuklina/java-explore-with-me pull request #3
Opened 2023-06-19 14:54 UTC by Natal1a-Chuklina

2023-06-20 17:33 UTC, z8q requested changes

2023-06-20 17:33 UTC, z8q commented on stats-service/server/src/main/java/ru/practicum/stats/model/EndpointHit.java
> +    public boolean equals(Object o) {
Тут можно посмотреть примеры, когда в сущностях переопределяется hashcode и equals:
https://thorben-janssen.com/ultimate-guide-to-implementing-equals-and-hashcode-with-hibernate/
Вот этот абзац:
As you can see, Java’s default equals() and hashCode() methods only produce the required result if the Hibernate Session ensures that there is only 1 Java object that represents a specific record in the database table. If you load your entities in multiple Sessions or if you work with detached entities, you need to override these methods. In all other cases, it’s better to rely on Java’s default implementation.

2023-06-20 17:33 UTC, z8q commented on stats-service/dto/pom.xml
> +    <artifactId>dto</artifactId>
Возможно у модуля стоит поменять название, 
если в перспективе будут хранится только дто, не знаю даже, стоит ли в отдельный модуль выносить

2023-06-21 04:03 UTC, Natal1a-Chuklina commented on stats-service/dto/pom.xml
> +    <artifactId>dto</artifactId>
Это является требованием из ТЗ.
![изображение](https://github.com/Natal1a-Chuklina/java-explore-with-me/assets/113743128/72f5b889-3e0d-46e5-a9be-49d1807a6a8b)

2023-06-21 04:15 UTC, Natal1a-Chuklina commented on stats-service/server/src/main/java/ru/practicum/stats/model/EndpointHit.java
> +    public boolean equals(Object o) {
Да, я еще раньше читала про особенности определения hashCode() и equals() у jpa сущностей, и методы в классе EndpointHit соответствуют требованиям из раздела (Using a Generated Primary Key) этой статьи.

2023-06-21 15:20 UTC, z8q approved these changes

2023-06-21 17:13 UTC, merged